samplesheet: "config/samples.tsv"

get_genome:
  database: "manual"
  assembly: "KF297339.1"
  fasta: "data/genome/KF297339.1.fasta"
  gff: "data/genome/KF297339.1.gff"
  gff_source_type:
    [
      "RefSeq": "gene",
      "RefSeq": "pseudogene",
      "RefSeq": "CDS",
      "Protein Homology": "CDS",
    ]

processing:
  tool: "trim_galore"
  fastp:
    extra: ""
  trim_galore:
    extra: "--gzip --paired"
  umi_tools_extract:
    enabled: true # Set to true to enable UMI extraction
    extra: "--bc-pattern=NNNNNNNN --bc-pattern2=NNNNNNNN"

mapping:
  tool: "star"
  bowtie2:
    index: ""
    extra: ""
  bwa_mem2:
    extra: ""
    sort: "samtools"
    sort_order: "coordinate"
    sort_extra: ""
  star:
    index: "--genomeSAindexNbases 7"
    extra: ""
  minimap2:
    index: ""
    extra: "-ax map-ont"
    sorting: "coordinate"
    sort_extra: ""
  samtools_sort:
    extra: "-m 4G"
  samtools_index:
    extra: ""
  umi_tools_dedup:
    enabled: true # Set to true to enable deduplication
    extra: "--paired" # or directional, cluster, adjacency, etc.

mapping_stats:
  gffread:
    extra: ""
  rseqc_infer_experiment:
    extra: ""
  rseqc_bam_stat:
    extra: ""
  deeptools_coverage:
    genome_size: 230000
    extra: ""

tsrs:
  tsrDetectR:
    method: "maxtss"
    window: 11
    background: 101
    threshold: 0.99

qc:
  multiqc:
    extra: "--verbose --dirs"
  fastqc:
    extra: "--quiet"

ucsc_trackhub:
  hub_name: "test"
  defaultPos: "KF297339.1:1-20000"
  short_label: "TEST trackhub"
  long_label: "TEST trackhub"
  genome: "HCMV TB40e BAC4 SV40-GFP"
  email: "aryazand@test.org"