samplesheet: "config/samples.tsv"

get_genome:
  database: "manual"
  assembly: "KF297339.1"
  fasta: "data/genome/KF297339.1.fasta"
  gff: "data/genome/KF297339.1.gff"
  gff_source_type:
    [
      "Genbank": "gene",
      "Genbank": "pseudogene",
      "Genbank": "CDS",
      "Protein Homology": "CDS",
    ]
  structure: 
    circular: 
      [
        'KF297339.1 Human herpesvirus 5 strain TB40/E clone Lisa, complete genome': 500
      ]


processing:
  tool: "trim_galore"
  fastp:
    extra: ""
  trim_galore:
    extra: "--gzip --paired"
  umi_tools_extract:
    enabled: true # Set to true to enable UMI extraction
    extra: "--bc-pattern=NNNNNNNN --bc-pattern2=NNNNNNNN"

mapping:
  tool: "star"
  bowtie2:
    index: ""
    extra: ""
  bwa_mem2:
    extra: ""
    sort: "samtools"
    sort_order: "coordinate"
    sort_extra: ""
  star:
    index: "--genomeSAindexNbases 7"
    extra: ""
  minimap2:
    index: ""
    extra: "-ax map-ont"
    sorting: "coordinate"
    sort_extra: ""
  samtools_sort:
    extra: "-m 4G"
  samtools_index:
    extra: ""
  umi_tools_dedup:
    enabled: true # Set to true to enable deduplication
    extra: "--paired" # or directional, cluster, adjacency, etc.

mapping_stats:
  gffread:
    extra: ""
  rseqc_infer_experiment:
    extra: ""
  rseqc_bam_stat:
    extra: ""
  deeptools_coverage:
    genome_size: 230000
    extra: ""

annotation:
  stringtie:
    ref_anno: "data/genome/KF297339.1.gff"
    strandedness: ""
    extra: "--nasc" #Keeps non poly-A RNA for output
  stringtie_merge:
    extra: ""
  gffcompare:
    extra: ""

tsrs:
  tsrDetectR:
    method: "maxtss"
    window: 11
    background: 101
    threshold: 0.99
  bedtools_merge:
    extra: "-s -d 10 -c 4,5,6 -o distinct,max,distinct"

qc:
  multiqc:
    extra: "--verbose --dirs"
  fastqc:
    extra: "--quiet"

ucsc_trackhub:
  gff3ToGenePred:
    genome: "-rnaNameAttr=gene"
  gtfToGenePred:
    stringtie: ""
  genePredToBigGenePred:
    stringtie: ""
    genome: ""
  bedToBigBed:
    TSRs: ""
    genome: "-type=bed12+8 -tab"
    stringtie: "-type=bed12+8 -tab"
  faToTwoBit:
    genome: ""
  hub_file:
    hub_name: "test"
    email: "aryazand@test.org"
    short_label: "TEST trackhub"
    long_label: "TEST trackhub"
  genomes:
    KF297339.1:
      organism: "Human Cytomegalovirus"
      scientificName: "Human Herpesvirus 5 strain TB40E"
      defaultPos: "KF297339.1:1-20000"
      description: "HCMV TB40E, clone Lisa"
      htmlDocumentation: "HCMV TB40E, clone Lisa (html string)"
      orderKey: 4800
      trackDb:
        annotation:
          track_name: "TB40"
          short_label: "HCMV TB40E"
          long_label: "HCMV TB40E, clone Lisa"
        bw:
          plus_color: "0,0,100"
          minus_color: "255,0,0"
          negateValues_for_minus_strand: "on" # on or off
        TSRs:
          track_name: "tsrs"
          shortLabel: "TSRs"
          longLabel: "Detected Transcription Start Regions"
